package com.seleniumboot.junit5;

import com.seleniumboot.ai.AiFailureAnalyzer;
import com.seleniumboot.api.SeleniumBootApi;
import com.seleniumboot.browser.BrowserContext;
import com.seleniumboot.browser.ConsoleErrorCollector;
import com.seleniumboot.client.ApiClient;
import com.seleniumboot.config.SeleniumBootConfig;
import com.seleniumboot.context.ScenarioContext;
import com.seleniumboot.driver.DriverManager;
import com.seleniumboot.healing.HealLog;
import com.seleniumboot.hooks.HookRegistry;
import com.seleniumboot.internal.SeleniumBootContext;
import com.seleniumboot.lifecycle.FrameworkBootstrap;
import com.seleniumboot.metrics.ExecutionMetrics;
import com.seleniumboot.network.NetworkMock;
import com.seleniumboot.recording.RecordingManager;
import com.seleniumboot.reporting.ScreenshotManager;
import com.seleniumboot.steps.StepLogger;
import com.seleniumboot.steps.StepStatus;
import com.seleniumboot.testdata.TestDataStore;
import com.seleniumboot.listeners.Retryable;
import com.seleniumboot.tracing.TraceRecorder;
import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.InvocationInterceptor;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolver;
import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
import org.openqa.selenium.WebDriver;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Optional;

/**
 * JUnit 5 extension providing the full Selenium Boot lifecycle.
 *
 * <p>Equivalent to {@code SuiteExecutionListener + TestExecutionListener} in TestNG.
 * Register via {@link EnableSeleniumBoot} or directly:
 * <pre>
 * {@literal @}ExtendWith(SeleniumBootExtension.class)
 * class LoginTest {
 *
 *     {@literal @}Test
 *     void validLogin(WebDriver driver) {   // parameter injection
 *         driver.get("https://example.com");
 *     }
 * }
 * </pre>
 *
 * <p>Lifecycle per test method:
 * <ol>
 *   <li>{@code beforeAll}  — bootstrap framework once per class (idempotent)</li>
 *   <li>{@code beforeEach} — create driver, start timing, notify hooks</li>
 *   <li>Test method executes (WebDriver injectable as parameter)</li>
 *   <li>{@code afterEach}  — screenshot on failure, record status, quit driver, cleanup</li>
 *   <li>{@code afterAll}   — quit per-suite driver when lifecycle=per-suite</li>
 * </ol>
 *
 * <p>Suite-level HTML report is generated by {@link SeleniumBootLauncherListener},
 * registered automatically via ServiceLoader.
 */
@SeleniumBootApi(since = "1.9.0")
public class SeleniumBootExtension
        implements BeforeAllCallback, AfterAllCallback,
                   BeforeEachCallback, AfterEachCallback,
                   ParameterResolver, InvocationInterceptor {

    @Override
    public void beforeAll(ExtensionContext context) {
        FrameworkBootstrap.initialize();
    }

    @Override
    public void beforeEach(ExtensionContext context) {
        String testId = testId(context);
        SeleniumBootContext.setCurrentTestId(testId);
        ExecutionMetrics.clearSteps(testId);
        ExecutionMetrics.markStart(testId);
        ExecutionMetrics.recordTestClass(testId, context.getRequiredTestClass().getSimpleName());
        ExecutionMetrics.recordDescription(testId, context.getDisplayName());

        DriverManager.createDriver();

        SeleniumBootConfig.Recording rec = SeleniumBootContext.getConfig().getRecording();
        if (rec != null && rec.isEnabled()) {
            RecordingManager.start(DriverManager.getDriver(), rec.getFps(), rec.getMaxDurationSeconds());
        }

        if (ConsoleErrorCollector.isEnabled()) {
            ConsoleErrorCollector.injectShim();
        }

        HookRegistry.onTestStart(testId);
    }

    @Override
    public void afterEach(ExtensionContext context) {
        String testId   = SeleniumBootContext.getCurrentTestId();
        String testName = context.getRequiredTestMethod().getName();
        Optional<Throwable> failure = context.getExecutionException();

        try {
            if (failure.isPresent()) {
                Throwable cause = failure.get();

                if (ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));
                }

                String screenshotPath = ScreenshotManager.capture(testName);
                ExecutionMetrics.recordScreenshot(testId, screenshotPath);
                ExecutionMetrics.recordError(testId, cause);
                ExecutionMetrics.recordStatus(testId, "FAILED");
                ExecutionMetrics.markEnd(testId);

                saveTraceIfEnabled(testId, testName, false);
                runAiAnalysisIfEnabled(testId);
                RecordingManager.saveOnFailure(testId);
                HookRegistry.onTestFailure(testId, cause);

            } else {
                if (ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));

                    boolean failOnErrors = SeleniumBootContext.getConfig().getBrowser() != null
                            && SeleniumBootContext.getConfig().getBrowser().isFailOnConsoleErrors();
                    if (failOnErrors && !errors.isEmpty()) {
                        ExecutionMetrics.recordStatus(testId, "FAILED");
                        ExecutionMetrics.markEnd(testId);
                        RecordingManager.stop();
                        HookRegistry.onTestFailure(testId,
                                new AssertionError("Console errors detected: " + errors.get(0)));
                        return;
                    }
                }

                ExecutionMetrics.recordStatus(testId, "PASSED");
                ExecutionMetrics.markEnd(testId);
                saveTraceIfEnabled(testId, testName, true);
                RecordingManager.stop();
                HookRegistry.onTestEnd(testId, "PASSED");
            }
        } finally {
            ScenarioContext.clear();
            TestDataStore.clear();
            ApiClient.clearGlobalAuth();
            BrowserContext.clear();
            NetworkMock.cleanup();
            if (DriverManager.shouldQuitAfterTest()) DriverManager.quitDriver();
            SeleniumBootContext.clearCurrentTestId();
        }
    }

    @Override
    public void afterAll(ExtensionContext context) {
        DriverManager.quitAllSuiteDrivers();
        DriverManager.quitDriver();
        HealLog.export();
    }

    // ── Retry via InvocationInterceptor ───────────────────────────────────

    @Override
    public void interceptTestMethod(
            Invocation<Void> invocation,
            ReflectiveInvocationContext<Method> invocationContext,
            ExtensionContext context) throws Throwable {

        int maxRetries = resolveMaxRetries(context);

        if (maxRetries <= 0) {
            invocation.proceed();
            return;
        }

        String testId = testId(context);
        Throwable lastFailure = null;

        for (int attempt = 1; attempt <= maxRetries + 1; attempt++) {
            try {
                if (attempt == 1) {
                    invocation.proceed();
                } else {
                    // Record retry, recreate driver, re-invoke via reflection
                    ExecutionMetrics.recordRetry(testId);
                    ExecutionMetrics.clearSteps(testId);
                    try { DriverManager.quitDriver(); } catch (Exception ignored) {}
                    DriverManager.createDriver();

                    Method m = invocationContext.getExecutable();
                    m.setAccessible(true);
                    Object[] args = invocationContext.getArguments().stream()
                            .map(a -> a instanceof WebDriver ? DriverManager.getDriver() : a)
                            .toArray();
                    try {
                        m.invoke(context.getRequiredTestInstance(), args);
                    } catch (InvocationTargetException e) {
                        throw e.getCause();
                    }
                }
                return; // attempt succeeded
            } catch (Throwable t) {
                lastFailure = t;
            }
        }
        throw lastFailure;
    }

    private int resolveMaxRetries(ExtensionContext context) {
        // 1. Method-level @Retryable
        Retryable onMethod = context.getRequiredTestMethod().getAnnotation(Retryable.class);
        if (onMethod != null) {
            return onMethod.maxAttempts() >= 0 ? onMethod.maxAttempts() : configMaxRetries();
        }
        // 2. Class-level @Retryable
        Retryable onClass = context.getRequiredTestClass().getAnnotation(Retryable.class);
        if (onClass != null) {
            return onClass.maxAttempts() >= 0 ? onClass.maxAttempts() : configMaxRetries();
        }
        // 3. Global config
        return configMaxRetries();
    }

    private int configMaxRetries() {
        try {
            SeleniumBootConfig.Retry retry = SeleniumBootContext.getConfig().getRetry();
            if (retry == null || !retry.isEnabled()) return 0;
            return Math.max(0, retry.getMaxAttempts());
        } catch (Exception e) {
            return 0;
        }
    }

    // ── Parameter injection — WebDriver as test method parameter ──────────

    @Override
    public boolean supportsParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return WebDriver.class.isAssignableFrom(paramCtx.getParameter().getType());
    }

    @Override
    public Object resolveParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return DriverManager.getDriver();
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    static String testId(ExtensionContext context) {
        return context.getRequiredTestClass().getName()
                + "#"
                + context.getRequiredTestMethod().getName();
    }

    private void saveTraceIfEnabled(String testId, String testName, boolean isPassing) {
        try {
            SeleniumBootConfig.Tracing tracing = SeleniumBootContext.getConfig().getTracing();
            if (tracing == null || !tracing.isEnabled()) return;
            if (isPassing && !tracing.isCaptureOnPass()) return;
            TraceRecorder.save(testId, testName);
        } catch (Exception ignored) {}
    }

    private void runAiAnalysisIfEnabled(String testId) {
        try {
            String pageUrl = null, pageTitle = null;
            try {
                WebDriver d = DriverManager.getDriver();
                if (d != null) { pageUrl = d.getCurrentUrl(); pageTitle = d.getTitle(); }
            } catch (Exception ignored) {}
            AiFailureAnalyzer.analyze(testId, pageUrl, pageTitle);
        } catch (Exception ignored) {}
    }
}
